{
 "swagger": "2.0",
 "info": {
  "title": "EVE Swagger Interface",
  "description": "An OpenAPI for EVE Online",
  "version": "0.8.0"
 },
 "host": "esi.tech.ccp.is",
 "schemes": [
  "https"
 ],
 "securityDefinitions": {
  "evesso": {
   "type": "oauth2",
   "authorizationUrl": "https://login.eveonline.com/oauth/authorize",
   "flow": "implicit",
   "scopes": {
    "esi-alliances.read_contacts.v1": "EVE SSO scope esi-alliances.read_contacts.v1",
    "esi-assets.read_assets.v1": "EVE SSO scope esi-assets.read_assets.v1",
    "esi-assets.read_corporation_assets.v1": "EVE SSO scope esi-assets.read_corporation_assets.v1",
    "esi-bookmarks.read_character_bookmarks.v1": "EVE SSO scope esi-bookmarks.read_character_bookmarks.v1",
    "esi-bookmarks.read_corporation_bookmarks.v1": "EVE SSO scope esi-bookmarks.read_corporation_bookmarks.v1",
    "esi-calendar.read_calendar_events.v1": "EVE SSO scope esi-calendar.read_calendar_events.v1",
    "esi-calendar.respond_calendar_events.v1": "EVE SSO scope esi-calendar.respond_calendar_events.v1",
    "esi-characters.read_agents_research.v1": "EVE SSO scope esi-characters.read_agents_research.v1",
    "esi-characters.read_blueprints.v1": "EVE SSO scope esi-characters.read_blueprints.v1",
    "esi-characters.read_chat_channels.v1": "EVE SSO scope esi-characters.read_chat_channels.v1",
    "esi-characters.read_contacts.v1": "EVE SSO scope esi-characters.read_contacts.v1",
    "esi-characters.read_corporation_roles.v1": "EVE SSO scope esi-characters.read_corporation_roles.v1",
    "esi-characters.read_fatigue.v1": "EVE SSO scope esi-characters.read_fatigue.v1",
    "esi-characters.read_fw_stats.v1": "EVE SSO scope esi-characters.read_fw_stats.v1",
    "esi-characters.read_loyalty.v1": "EVE SSO scope esi-characters.read_loyalty.v1",
    "esi-characters.read_medals.v1": "EVE SSO scope esi-characters.read_medals.v1",
    "esi-characters.read_notifications.v1": "EVE SSO scope esi-characters.read_notifications.v1",
    "esi-characters.read_opportunities.v1": "EVE SSO scope esi-characters.read_opportunities.v1",
    "esi-characters.read_standings.v1": "EVE SSO scope esi-characters.read_standings.v1",
    "esi-characters.read_titles.v1": "EVE SSO scope esi-characters.read_titles.v1",
    "esi-characters.write_contacts.v1": "EVE SSO scope esi-characters.write_contacts.v1",
    "esi-characterstats.read.v1": "EVE SSO scope esi-characterstats.read.v1",
    "esi-clones.read_clones.v1": "EVE SSO scope esi-clones.read_clones.v1",
    "esi-clones.read_implants.v1": "EVE SSO scope esi-clones.read_implants.v1",
    "esi-contracts.read_character_contracts.v1": "EVE SSO scope esi-contracts.read_character_contracts.v1",
    "esi-contracts.read_corporation_contracts.v1": "EVE SSO scope esi-contracts.read_corporation_contracts.v1",
    "esi-corporations.read_blueprints.v1": "EVE SSO scope esi-corporations.read_blueprints.v1",
    "esi-corporations.read_contacts.v1": "EVE SSO scope esi-corporations.read_contacts.v1",
    "esi-corporations.read_container_logs.v1": "EVE SSO scope esi-corporations.read_container_logs.v1",
    "esi-corporations.read_corporation_membership.v1": "EVE SSO scope esi-corporations.read_corporation_membership.v1",
    "esi-corporations.read_divisions.v1": "EVE SSO scope esi-corporations.read_divisions.v1",
    "esi-corporations.read_facilities.v1": "EVE SSO scope esi-corporations.read_facilities.v1",
    "esi-corporations.read_fw_stats.v1": "EVE SSO scope esi-corporations.read_fw_stats.v1",
    "esi-corporations.read_medals.v1": "EVE SSO scope esi-corporations.read_medals.v1",
    "esi-corporations.read_outposts.v1": "EVE SSO scope esi-corporations.read_outposts.v1",
    "esi-corporations.read_standings.v1": "EVE SSO scope esi-corporations.read_standings.v1",
    "esi-corporations.read_starbases.v1": "EVE SSO scope esi-corporations.read_starbases.v1",
    "esi-corporations.read_structures.v1": "EVE SSO scope esi-corporations.read_structures.v1",
    "esi-corporations.read_titles.v1": "EVE SSO scope esi-corporations.read_titles.v1",
    "esi-corporations.track_members.v1": "EVE SSO scope esi-corporations.track_members.v1",
    "esi-fittings.read_fittings.v1": "EVE SSO scope esi-fittings.read_fittings.v1",
    "esi-fittings.write_fittings.v1": "EVE SSO scope esi-fittings.write_fittings.v1",
    "esi-fleets.read_fleet.v1": "EVE SSO scope esi-fleets.read_fleet.v1",
    "esi-fleets.write_fleet.v1": "EVE SSO scope esi-fleets.write_fleet.v1",
    "esi-industry.read_character_jobs.v1": "EVE SSO scope esi-industry.read_character_jobs.v1",
    "esi-industry.read_character_mining.v1": "EVE SSO scope esi-industry.read_character_mining.v1",
    "esi-industry.read_corporation_jobs.v1": "EVE SSO scope esi-industry.read_corporation_jobs.v1",
    "esi-industry.read_corporation_mining.v1": "EVE SSO scope esi-industry.read_corporation_mining.v1",
    "esi-killmails.read_corporation_killmails.v1": "EVE SSO scope esi-killmails.read_corporation_killmails.v1",
    "esi-killmails.read_killmails.v1": "EVE SSO scope esi-killmails.read_killmails.v1",
    "esi-location.read_location.v1": "EVE SSO scope esi-location.read_location.v1",
    "esi-location.read_online.v1": "EVE SSO scope esi-location.read_online.v1",
    "esi-location.read_ship_type.v1": "EVE SSO scope esi-location.read_ship_type.v1",
    "esi-mail.organize_mail.v1": "EVE SSO scope esi-mail.organize_mail.v1",
    "esi-mail.read_mail.v1": "EVE SSO scope esi-mail.read_mail.v1",
    "esi-mail.send_mail.v1": "EVE SSO scope esi-mail.send_mail.v1",
    "esi-markets.read_character_orders.v1": "EVE SSO scope esi-markets.read_character_orders.v1",
    "esi-markets.read_corporation_orders.v1": "EVE SSO scope esi-markets.read_corporation_orders.v1",
    "esi-markets.structure_markets.v1": "EVE SSO scope esi-markets.structure_markets.v1",
    "esi-planets.manage_planets.v1": "EVE SSO scope esi-planets.manage_planets.v1",
    "esi-planets.read_customs_offices.v1": "EVE SSO scope esi-planets.read_customs_offices.v1",
    "esi-search.search_structures.v1": "EVE SSO scope esi-search.search_structures.v1",
    "esi-skills.read_skillqueue.v1": "EVE SSO scope esi-skills.read_skillqueue.v1",
    "esi-skills.read_skills.v1": "EVE SSO scope esi-skills.read_skills.v1",
    "esi-ui.open_window.v1": "EVE SSO scope esi-ui.open_window.v1",
    "esi-ui.write_waypoint.v1": "EVE SSO scope esi-ui.write_waypoint.v1",
    "esi-universe.read_structures.v1": "EVE SSO scope esi-universe.read_structures.v1",
    "esi-wallet.read_character_wallet.v1": "EVE SSO scope esi-wallet.read_character_wallet.v1",
    "esi-wallet.read_corporation_wallets.v1": "EVE SSO scope esi-wallet.read_corporation_wallets.v1"
   }
  }
 },
 "paths": {
  "/v1/characters/{character_id}/location/": {
   "get": {
    "description": "Information about the characters current location. Returns the current solar system id, and also the current station or structure ID if applicable.\n\n---\n\nThis route is cached for up to 5 seconds",
    "summary": "Get character location",
    "tags": [
     "Location"
    ],
    "security": [
     {
      "evesso": [
       "esi-location.read_location.v1"
      ]
     }
    ],
    "operationId": "get_characters_character_id_location",
    "x-cached-seconds": 5,
    "x-alternate-versions": [
     "dev",
     "legacy",
     "v1"
    ]
   }
  },
  "/v1/characters/{character_id}/ship/": {
   "get": {
    "description": "Get the current ship type, name and id\n\n---\n\nThis route is cached for up to 5 seconds",
    "summary": "Get current ship",
    "tags": [
     "Location"
    ],
    "security": [
     {
      "evesso": [
       "esi-location.read_ship_type.v1"
      ]
     }
    ],
    "operationId": "get_characters_character_id_ship",
    "x-cached-seconds": 5,
    "x-alternate-versions": [
     "dev",
     "legacy",
     "v1"
    ]
   }
  },
  "/v2/universe/stations/{station_id}/": {
   "get": {
    "description": "Get information on a station\n\n---\n\nThis route is cached for up to 300 seconds",
    "summary": "Get station information",
    "tags": [
     "Universe"
    ],
    "operationId": "get_universe_stations_station_id",
    "x-cached-seconds": 300,
    "x-alternate-versions": [
     "dev",
     "v2"
    ]
   }
  },
  "/v1/universe/structures/{structure_id}/": {
   "get": {
    "description": "Returns information on requested structure, if you are on the ACL. Otherwise, returns \"Forbidden\" for all inputs.\n\n---\n\nThis route is cached for up to 3600 seconds",
    "summary": "Get structure information",
    "tags": [
     "Universe"
    ],
    "security": [
     {
      "evesso": [
       "esi-universe.read_structures.v1"
      ]
     }
    ],
    "operationId": "get_universe_structures_structure_id",
    "x-cached-seconds": 3600,
    "x-alternate-versions": [
     "dev",
     "legacy",
     "v1"
    ]
   }
  },
  "/v3/universe/systems/{system_id}/": {
   "get": {
    "description": "Get information on a solar system\n\n---\n\nThis route expires daily at 11:05",
    "summary": "Get solar system information",
    "tags": [
     "Universe"
    ],
    "operationId": "get_universe_systems_system_id",
    "x-alternate-versions": [
     "dev",
     "v3"
    ]
   }
  }
 }
}