# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corputils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpstats',
            options={'default_permissions': ('add', 'delete', 'view'), 'permissions': (('corp_apis', 'Can view API keys of members of their corporation.'), ('alliance_apis', 'Can view API keys of members of their alliance.'), ('blue_apis', 'Can view API keys of members of blue corporations.')), 'verbose_name': 'Corp stats'},
        ),
    ]
