# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='objective',
            field=models.CharField(choices=[('Friendly', 'Friendly'), ('Hostile', 'Hostile'), ('Neutral', 'Neutral')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='timer',
            name='structure',
            field=models.CharField(choices=[('I-HUB', 'I-HUB'), ('POCO', 'POCO'), ('POS[S]', 'POS[S]'), ('POS[M]', 'POS[M]'), ('POS[L]', 'POS[L]'), ('Station', 'Station'), ('TCU', 'TCU'), ('Other', 'Other')], default='', max_length=254),
        ),
    ]
