# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Auth / TS Group',
            },
        ),
        migrations.CreateModel(
            name='DiscordAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.TextField(default={})),
                ('service', models.CharField(choices=[(b'discourse', b'discourse'), (b'discord', b'discord')], max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MumbleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('pwhash', models.CharField(max_length=40)),
                ('groups', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSgroup',
            fields=[
                ('ts_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ts_group_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'TS Group',
            },
        ),
        migrations.CreateModel(
            name='UserTSgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_group', models.ManyToManyField(to='services.TSgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User TS Group',
            },
        ),
        migrations.AddField(
            model_name='authts',
            name='ts_group',
            field=models.ManyToManyField(to='services.TSgroup'),
        ),
    ]
