# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupmanagement', '0003_default_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='status',
            field=models.CharField(default='Pending', max_length=254),
        ),
    ]
